### ISSUE TITLE
Switching between storyteller and player resets video/audio settings

### ISSUE THREAD

**Issue by bigheadzach** [ThePandemoniumInstitute/botc-release#122]
Using Chrome 120.0.6099.216 on a MBP running Ventura 13.6.3, if you switch/are switched out of or into the Storyteller position, your selections for audio and video input are reset to defaults. For those that have multiple sources due to configuration over various apps, this is a minor annoyance - you can correct it but must remember to do so each time.

**Comment by bra1n** [comment]
Hi Zach, the selected mic and cam device should be save across sessions and also when switching from playing to spectating or storytelling. I've just tested this and it worked for me. It might be a mac or device issue? Maybe your cam or mic devices are virtual and have changing IDs? Could you maybe try recording a video of the issue so that I can see what exactly is not working?
