### ISSUE TITLE
Can't hear people after "Follow Storyteller"

### ISSUE THREAD

**Issue by Unbaloav** [ThePandemoniumInstitute/botc-release#125]
**Describe the bug**
When I am spectating a game with grim access and use the "Follow Storyteller" or "Follow Player" option after a few jumps through chats the sound sometimes bugs out, so that I can't hear the people in the chat. Jumping manually to Townsquare and back in fixes it.

**To Reproduce**
1. Be a spectator with grim access 
2. Use the Follow Storyteller option
3. Let the ST jump between several private chats
4. Encounter the error (not hearing the people in the chat)

**Standalone app (please complete the following information):**
- Version 3.21.3

 (Edit: Just noticed that actually, when it happens after exactly 5 seconds the sound sets in by itself.)

**Comment by bra1n** [comment]
Hey @Unbaloav, thank you for this bug report! Would it be possible for you to record a video of this? Is it happening consistently or only sometimes? Are there any error messages in the console? If the sound returns after a few seconds, then that might be just a connection latency issue, rather than an actual bug.

**Comment by Unbaloav** [comment]
It only happens sometimes, like every 2nd day and I am starting to think that it is just a connection latency issue, which confuses me because it doesn't happen if I follow the ST manually.

**Comment by bra1n** [comment]
Alright, I was able to reproduce the bug and will fix it with the next update. Thanks! :+1:
