### ISSUE TITLE
Extra reminder tokens

### ISSUE THREAD

**Issue by Ash-42** [ThePandemoniumInstitute/botc-release#126]
**Describe the bug**
When viewing a game as a spectator with grim access, every player gained an extra, smaller, blank reminder token that can't be deleted. They remained even after refreshing the page, removing grim access, clearing the grim, joining as a player, leaving and rejoining the lobby, and joining other lobbies, but went away when I closed and reopened my browser.

**Screenshots**
![Screenshot 2024-02-25 223112](https://github.com/ThePandemoniumInstitute/botc-release/assets/161276881/acbfb750-2366-4657-99be-be9215fb0869)

**Browser app (please complete the following information):**
 - OS: Window 11
 - Browser: Microsoft Edge
 - Version 3.21.3

**Additional context**
- Game session name: #trouble-functioning
- Date and time when it happened: February 25th, 2024, 10-11pm CST

**Comment by bra1n** [comment]
Hey @Ash-42, what you're looking at there is the "touch device" view of the app. It is shown when your browser tells the app that it doesn't have a mouse but rather is a touch interface, like on a tablet or smartphone. Did you maybe accidentally enable this mode or use the app on such a device?
The "new" reminder tokens are usually only visible when you hover over them with a mouse, but on touch devices you obviously can't do that, which is why they're permanently visible there.
