### ISSUE TITLE
Wrong player token alignment and clock hand points in the wrong direction

### ISSUE THREAD

**Issue by kurthuwig** [ThePandemoniumInstitute/botc-release#148]
Please see this screenshot:

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/2757758/fbcead2e-1992-4976-89f1-6c936d0345e8)

The player tokens in the lower half are not aligned correctly and so is the hand of the clock. The magnitude of misaligned changes with the size of the browser window and gets worse when I make it smaller:

![image](https://github.com/ThePandemoniumInstitute/botc-release/assets/2757758/c5b35227-a0e8-4179-8b09-25bdaafdc906)

**Browser app (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 123.0.6312.58

**Comment by bra1n** [comment]
Hey Kurt,
thanks for the bug report! Unfortunately, this is a side-effect caused by the "player" elements in the circle being of different heights. The issue becomes more apparent, the smaller your app window is, because the player elements will have a mostly static height independent of that. There isn't much that I can do about it, because aligning them all the same would mean that players with bigger name boxes would have their names go outside the app window on smaller resolutions.
