### ISSUE TITLE
Webcam prompt possible bug

### ISSUE THREAD

**Issue by real-JOSH** [ThePandemoniumInstitute/botc-release#151]
**Describe the bug**
When launching the app, and logging in, if you are using your webcam in another application (discord, in this example) you receive console errors.  I feel that the application shouldn't be prompting for video device access until I ask the app to utilize video.  Seems suspect, or a bug.

**Expected behavior**
Suggestion, make the size of the settings menu flex-based instead of expanding to fit its child elements as navigating through the tabs resizes the menu (by a large amount) and makes for a poor user experience.

Also make the menu more opaque - reading the menu options is difficult, or busy, in some instances

**Browser app (please complete the following information):**
 - Windows 11 OS
 - Browser Chroms
 - Version unknown

**Comment by bra1n** [comment]
Hi Josh,
unfortunately, the app needs to request cam / mic access right away, in order to be able to list your cam / mic devices. It doesn't actually start *using* the mic or cam until you take a seat in a game, and the browser should indicate as much once you've given permission. I don't think this behavior is going to change for the above reasons.

As for the second part - that seems like a completely unrelated issue? I've decreased the menu transparency because you were right that it was a bit too transparent, but as for the settings being jumpy: not sure how to improve that. If I force all of them to be the same height, there will be a lot of unused space, which would look equally weird. Aligning them to the same position would also be problematic, since they have to work on many different screen sizes and could go off screen that way. It's unfortunately a side-effect of trying to create an interface that works on all screens equally well...

**Comment by real-JOSH** [comment]
Thank you for the fast reply. I was also looking for the bug hand!!! I
appreciate all that you do and how well the app works.

**Comment by bra1n** [comment]
Fair, but neither of those were actual bugs. ;-)
