### ISSUE TITLE
[BUG] I can send a message to Public as a spectator

### ISSUE THREAD

**Issue by Hawes0me** [ThePandemoniumInstitute/botc-release#169]
### Description

If a spectator sends a message to the lobby via direct interaction with the BoTC App websocket, they can successfully send a message as a spectator to the Public chat.

### Steps to reproduce

Here is the request that one can replay to the websocket directly:

`42/<lobby name>,["message","textMessage",{"message":"message to the lobby as a spectator","recipientId":""}]`

### Browser

Chrome

### Operating System

Windows

### Date and Time

Apr 25th 2:30PM EST

**Comment by bra1n** [comment]
Hey @Hawes0me thanks for the bug report! While it is technically true that they can send these, the players in the game will not see these messages. Their client filters out any messages from spectators. With the next update, these messages will also be filtered on the server side, so that they are not even reaching the clients of the players anymore.

**Comment by Hawes0me** [comment]
Can I get the bug hand for reporting this?

**Comment by bra1n** [comment]
Sure, send me a DM on Discord (@bra1n) or an email to support@botc.app
