### ISSUE TITLE
Disable text chat during vote to allow SPACEBAR to raise / lower hand

### ISSUE THREAD

**Issue by StewieGriffin** [ThePandemoniumInstitute/botc-release#199]
### Description

After nominations, when voting starts (the clock hand starts moving), if a player is focused on the chat window, the spacebar does not work for voting (a space is just added in the chat window).
This has influenced a few games I've played.

An easy fix would be for the app to automatically remove focus from the chat (or disable the chat window) during voting.

### Steps to reproduce

1. Player starts typing something in chat
2. ST starts the vote
3. Player presses --spacebar-- trying to vote, but a space is just added in chat and vote doesn't count

### Browser

Chrome

### Operating System

Windows

### Date and Time

July, 25, 01h00 GMT

**Comment by bra1n** [comment]
Hi there, this isn't really a bug - when you are entering a chat message, none of the shortcuts are working, because you probably don't intend to use a shortcut if you press the associated letter key. With the latest update, you can tab out of the chat box by pressing TAB, which allows your shortcuts to be used again.
Disabling text chat during a vote is probably a sensible feature request, but I'll have to think about it.

**Comment by Unbaloav** [comment]
I would disagree with this, since people (at least me) sometimes like to add something to an accusation or defense via chat if it isn't possible to add something verbaly, because one wouldn't like to make the ST adding a Hell's Librarian because it is getting too chaotic. Also if you start writing something in chat and then a nom starts it would be a bit annoying if can't continue writing it.

**Comment by StewieGriffin** [comment]
A solution for that would be to add it as an option in Settings, so players who want the feature can enable it without annoying those who don't.

**Comment by bra1n** [comment]
> I would disagree with this, since people (at least me) sometimes like to add something to an accusation or defense via chat if it isn't possible to add something verbaly, because one wouldn't like to make the ST add a Hell's Librarian because it is getting too chaotic. (Or one just isn't able to talk over others.) Also if you start writing something in chat and then a nom starts it would be a bit annoying if you can't continue writing it.

What I meant would only apply to the actual vote though - during the accusation and defense, people would still be able to chat. As soon as the vote itself begins, the text chat could be disabled and people could use their vote shortcut, for example.

**Comment by justincaseit** [comment]
Now with the new feature where chat is disabled.. I've had many interactions (myself and in games I've in) where users have left seats, spent votes by accident, etc.

This happens when the vote is started while the user is typing. Text chat gets disabled and the shortcuts are used without their knowledge.
