### ISSUE TITLE
[BUG] Co-ST night death shrouds don't solidify when clicked

### ISSUE THREAD

**Issue by Shad0wSlam** [ThePandemoniumInstitute/botc-release#202]
### Description

When an ST marks a player with a death shroud during the night, and then marks them with the death shroud in the morning, other STs will not see the death shroud solidified.

### Steps to reproduce

1. Have two STs in a session
2. During the night, the first ST marks a player as dead
3. During the day, the same ST marks them as dead again so that players can see the death shroud
4. Observe that the other ST still sees the death shroud as transparent
![image](https://github.com/user-attachments/assets/179af029-39e0-46e1-9e52-c1df2c4904d1)

### Browser

Chrome

### Operating System

Windows

### Date and Time

August 9th, 10pm, BST

### Game Session

ellie

**Comment by bra1n** [comment]
@Shad0wSlam Thanks for the bug report! I tested it on Chrome (Linux) and was unable to reproduce it - whenever I add shrouds at night and then make them visible the next day, they are updated correctly for the other ST in the session.
If you can see them with an eye icon on them, that is not crossed out, it would also mean that this is a shroud that the ST _removed_ at night and has not yet "taken off" during the day. Could you please try again yourself to see if the bug is still happening for you?

**Comment by bra1n** [comment]
Closed due to inactivity.
