### ISSUE TITLE
[FEATURE] Add chat server "load" (CPU) to game "Chat Server" drop-down.

### ISSUE THREAD

**Issue by genestealer** [ThePandemoniumInstitute/botc-release#211]
### What problem are you trying to solve?

Ping is not a good representation of server load, and confuses many people to think the server is not highly loaded. I.E. The ignore the user count.

### Describe the solution you'd like

Add "Server Load" I.E. CPU load. As an extra metric to the drop-down dialog.
Add a "Server Status" webpage, to see the "health" of the servers.

**Comment by bra1n** [comment]
Hi genestealer,
thanks for the suggestion! You're right, ping alone is not a decent enough indicator, which is why both the actual server load and the number of currently connected users are factored into the automatically recommended server (and the server sort order)! If you mouse over the status indicator (usually a green circle) of a chat server, you'll see the current server load. :-)
![image](https://github.com/user-attachments/assets/adb15470-4023-43d5-b5eb-305650e8cc0c)
