### ISSUE TITLE
[BUG] Center of the screen gets very crowded making it difficult to hover over tokens or see player count info

### ISSUE THREAD

**Issue by Killectro** [ThePandemoniumInstitute/botc-release#216]
### Description

During certain times such as when votes are running or when there are lots of tokens on-screen it becomes difficult if not impossible to hover over certain parts of the UI; for instance to see the player/outsider count.

### Steps to reproduce

1. go to town square with people in it
2. mouse over a player token on grim
3. attempt to mouse over player count popup in the center

### Browser

Chrome

### Operating System

Mac

### Date and Time

Sept 5 2024 any time EST

**Comment by bra1n** [comment]
That's not really a bug but a result of the new interface. You can still access the town square info by pressing "T". Alernatively, try decreasing the token size in the settings - that should also give you more space to work with. :-)

**Comment by Pratyush0015** [comment]
Not only mac but android users are also greatly affected by this update making some of features unavailable that earlier were. Including me I won't be able to play on this app if not fixed.

**Comment by bra1n** [comment]
Unfortunately, it's impossible to always account for all screen sizes and setups with any new change. The most recent change that added user avatars also meant that there was more "content" that needed to be shown on the screen, pushing the existing information further inwards. Due to this, accessing the central "town info" box became hard and harder, as the area to mouse-over shrunk further.
We've now made the decision to relegate this info to the town square mode altogether (press T by default to get there), which frees up the space and makes using the app more streamlined. I'm sorry that this has caused you troubles with playing on the app, however this change is most likely not going to be reverted.
