### ISSUE TITLE
[FEATURE] Lil'monsta v Widow/Spy v Magicion

### ISSUE THREAD

**Issue by humanpala** [ThePandemoniumInstitute/botc-release#235]
### What problem are you trying to solve?

Spy and Widow can see all other minion if lil'monsta exsist so they can know who is the magicion

### Describe the solution you'd like

Make a new jinx. if spy / widow and lil' monsta and magicion in the play then the spy / widow do not see neidher the  magicion nor the other minions

**Comment by boomjamsie** [comment]
Thanks for raising this concern! Currently, as a policy we do not write jinxes for three-way interactions. That's not to say it will never happen, but right now, we don't have the capacity to jinx every niche interaction between more than two characters at once! Since this would be a jinx between the Spy/Widow, Lil' Monsta, and Magician, that would be a three-way jinx and falls outside the realm of what we currently publish. That said, you are always welcome to house-rule interesting interactions like this to make the game more fun for your players!
