### ISSUE TITLE
[FEATURE] Amnesiac abilities altering setup to add multiple amnesiacs

### ISSUE THREAD

**Issue by Steiniearsenal** [ThePandemoniumInstitute/botc-release#239]
### What problem are you trying to solve?

I've been working on a script that would require the possibility of multiple amnesiacs granted by their ability having a setup condition such as [+0 to +2 Amnesiacs] much like the Village Idiot, but it is not currently possible to setup a game on the app this way.

The "How to run" section of the wiki for the Amnesiac states: "**While setting up the game**, decide what ability the Amnesiac player has." Currently, the app doesn't allow for this to it's full capacity.

### Describe the solution you'd like

Allow an option to duplicate characters within the settings or a trigger when the Amnesiac is on the script as per other characters with such effects.

### Alternatives you have considered

Currently the option to pass out multiple duplicates of the same character type are locked to:

1. Characters that have it built into their specific ability (Legion, Riot & Village Idiot)
2. Through using the Athiest allowing all roles to be duplicated, making it mandatory to have Athiest in the selection during setup. I wasn't intending for my script to have to be an athiest script.
3. Homebrew recreations of TPI characters.
4. Use of the Gardener, which can affect the intended amnesiac ability and one players knowledge of the game state.

Options 2, 3 & 4 are the current workarounds but are not simple or without compromise.

**Comment by bra1n** [comment]
Hey @Steiniearsenal, thank you for your feature request! Unfortunately, this is something that will not be added to the app. While you can give Amnesiacs a setup ability, it is a rather niche thing to do. Even more so since doubling character tokens is something that is also not possible in the physical game. As such, we want to keep the online app as close to the physical game as possible, to allow our fans to switch from one medium to the other without having to relearn too much.

If you really want to run Amnesiac that way, you can always double any and all character tokens by adding a Gardener Fabled to the game before handing out characters, or by Bootlegging your own Homebrew Amnesiac script that allows the Storyteller to duplicate any and all characters from the script.

**Comment by Steiniearsenal** [comment]
I appreciate the response but to do think that what you've said contradicts the functionality of the Athiest in the app currently since that can allow the duplication of all characters in setup. I also play with a few groups and it is very common to have numerous people with a Grim so multiple tokens can be used in games if people really do want to make it happen (a friend of mine ran an in person Athiest with 6 Damsels last week for example).

Either way I will respect the outcome, understand the logic, and have found my solution through bootlegging in the meantime.
