### ISSUE TITLE
The app functionality gone on mobile

### ISSUE THREAD

**Issue by ChloetheBarbarian** [ThePandemoniumInstitute/botc-release#264]
### Description

[BUG] the mobile usage of the app is kapoot for me now. I'm begging the most recent update be removed. I'm not longer allowed to vacate my seat and if I touch the screen even momentarily it raises my hand and there's nothing I can do about it

### Browser

Chrome

### Operating System

Android

### Date and Time

Yes

### Game Session

Yes

**Comment by bra1n** [comment]
Hey there, I'll adjust the swipe sensitivity to prevent accidental hand raising / lowering, but what exactly do you mean with no longer being able to vacate your seat?

**Comment by ChloetheBarbarian** [comment]
If I raise my hand I can't click on vacate seat. And if I click on vacate
seat while my hand isn't raised it raises my hand and I can't vacate seat

**Comment by bra1n** [comment]
Raising your hand (swipe up) or lowering your hand (swipe down) should not in any way interact with vacating your seat - clicking on a button should be possible even when you're accidentally raising your hand at the same time. I think there might be a different issue here. That said, I hope adjusting the swipe threshold with the next update will fix this for you as well, because mobile devices are officially not supported yet.
