### ISSUE TITLE
Don't allow drunk, marionette, lil monsta tokens to be sent out

### ISSUE THREAD

**Issue by bra1n** [ThePandemoniumInstitute/botc-release#44]
Would you be able to disallow tokens to be passed out if the drunk, marionette, lil monsta etc. tokens are selected; or have a popup that says the token is selected and it won't allow it to be passed out to characters. This will prevent unnecessary reracks

**Comment by SansCipher** [comment]
I agree with popup, disagree with preventing the send. TB+1, for example, famously uses drunk token to indicate that the player receiving the token has the +1. In those situations, sending out Drunk is deliberate and intentional

**Comment by VivaLaSam** [comment]
I think the compromise there would be to allow these tokens to be sent out only if the Bootlegger is in play (or Atheist I suppose). Overall I think it would be much better to not allow the Drunk token to be given out since it never would be with the typical game rules, rather than allow it specifically for a game with homebrew rules.

Alternatively, and maybe easier to implement, clicking "send characters" with these characters selected could bring up a pop up warning the ST and asking them to confirm one more time if they really want to send out these characters as-is.

**Comment by bra1n** [comment]
I really like the Bootlegger idea and I think it's the one I'll go with.
