### ISSUE TITLE
Video and Audio not working

### ISSUE THREAD

**Issue by brad-dunlap** [ThePandemoniumInstitute/botc-release#85]
Audio and video are not working at all. As ST I am stuck in headphones mode. I cannot even request private chats with seated players. No players are able to communicate. 

Sitting in any chair, no one is able to setup mic and cams or have the actually work. Unable to private chat. Text chat is actually working in game, but that is all. 

**Expected behavior**
Audio and video should work

**Screenshots**
<img width="1084" alt="image" src="https://github.com/ThePandemoniumInstitute/botc-release/assets/117024855/86dbbd13-74ec-46da-ae63-ffa389ce95ec">

Try to include a screenshot of the browser console as well, if you're using the browser version. (Windows/Linux: Shift + CTRL + J, Mac: Option + ⌘ + J or Option + ⌘ + C)

**Browser app (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version [e.g. 3.2.1]

**Additional context**

err_cert_date_invalid errors
<img width="622" alt="image" src="https://github.com/ThePandemoniumInstitute/botc-release/assets/117024855/c822c9f1-9a87-4453-b46c-3281560b8bed">

**Comment by bra1n** [comment]
Hi @brad-dunlap,

thank you very much for this perfect bug report! Due to the detailed information you provided, I was quickly able to figure out what was causing the issue and fixed it. Turns out the SSL Certificate on the US East chat server didn't refresh properly, so I restarted the server. It should be working again now. :-)
